#!/bin/bash

TESTCASES=(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29)
TESTDIR="examples"
WRONG="$(tput setaf 1)✗$(tput sgr0)"
CORRECT="$(tput setaf 2)✓$(tput sgr0)"
WARNING="$(tput setaf 3)⚠$(tput sgr0)"


function result {
    if [ 0 -lt "$1"  ]
    then
        echo "${WRONG}"
    else
        echo "${CORRECT}"
    fi
}

echo '# Compiling...'
if ! make
then
    echo ''
    echo 'Compile fail.'
    exit 1
fi
echo ''

echo '# Testing M Interpreter'

for TC in "${TESTCASES[@]}"
do
    TFILE="${TESTDIR}/test${TC}"

    printf "Test %s..." "${TC}"

    COMM="./run -resonly ${TFILE}.m > ${TFILE}.out"
    if [ -f "${TFILE}.in" ]
    then
        COMM="${COMM} < ${TFILE}.in"
    fi

    if eval "${COMM}"
    then
        if eval "diff ${TFILE}.ans ${TFILE}.out > /dev/null"
        then
            echo "${CORRECT}"
        else
            echo "${WRONG}"
            echo "== Answer =="
            cat "${TFILE}.ans"
            echo "== Output =="
            cat "${TFILE}.out"
        fi
    else
        echo "${WRONG}"
    fi
done

