#!/bin/bash

TESTCASES=(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24)
TC2=(1)
TC3=()
TESTDIR="examples"
EXDIR="exercises"
WRONG="$(tput setaf 1)✗$(tput sgr0)"
CORRECT="$(tput setaf 2)✓$(tput sgr0)"

function result {
    if [ "$1" == 1 ]
    then
        echo "${WRONG}"
    else
        echo "${CORRECT}"
    fi
}

echo '# Compiling...'
make

echo '# Testing k- interpreter'

for TC in "${TESTCASES[@]}"
do
    TFILE="${TESTDIR}/test${TC}"
    printf "Test %s..." "${TC}"
    COMM="./run ${TFILE}.k- > ${TFILE}.myout"
    if [ -f "${TFILE}.in" ]
    then
        COMM="${COMM} < ${TFILE}.in"
    fi

    eval "${COMM}"

    eval "diff ${TFILE}.out ${TFILE}.myout > /dev/null"
    result $?
done

echo "# Testing Exercise 2"
for TC in "${TC2[@]}"
do
    TFILE="${EXDIR}/test2-${TC}"
    printf "Test %s..." "${TC}"

    sed '$s/2017//' "${EXDIR}/ex2.k-" > "${TFILE}.tmp.k-" && cat "${TFILE}.k-" >> "${TFILE}.tmp.k-"
    COMM="./run ${TFILE}.tmp.k- > ${TFILE}.myout"

    eval "${COMM}"

    eval "diff ${TFILE}.out ${TFILE}.myout > /dev/null"
    result $?
done

echo "# Testing Exercise 3"
for TC in "${TC3[@]}"
do
    TFILE="${EXDIR}/test3-${TC}"
    printf "Test %s..." "${TC}"

    sed '$s/2017//' "${EXDIR}/ex3.k-" > "${TFILE}.tmp.k-" && cat "${TFILE}.k-" >> "${TFILE}.tmp.k-"
    COMM="./run ${TFILE}.tmp.k- > ${TFILE}.myout"

    eval "${COMM}"

    eval "diff ${TFILE}.out ${TFILE}.myout > /dev/null"
    result $?
done
