#!/bin/bash

TESTCASES=(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25)
ATESTCASES=(1)
TC2=(1 2 3 4 5 6 7 8 9 10)
TC3=(1 2 3 4)
TESTDIR="examples"
EXDIR="exercises"
WRONG="$(tput setaf 1)✗$(tput sgr0)"
CORRECT="$(tput setaf 2)✓$(tput sgr0)"

function result {
    if [ "$1" == 1 ]
    then
        echo "${WRONG}"
    else
        echo "${CORRECT}"
    fi
}

echo '# Compiling...'
if ! make
then
    echo ''
    echo 'Compile fail.'
    exit 1
fi
echo ''

echo '# Testing k- interpreter'

for TC in "${TESTCASES[@]}"
do
    TFILE="${TESTDIR}/test${TC}"
    printf "Test %s..." "${TC}"
    COMM="./run ${TFILE}.k- > ${TFILE}.out"
    if [ -f "${TFILE}.in" ]
    then
        COMM="${COMM} < ${TFILE}.in"
    fi

    eval "${COMM}"

    eval "diff ${TFILE}.ans ${TFILE}.out > /dev/null"
    result $?
done

echo '# Testing k- Advanced testcase : Possibly TA not score these testcases'
for TC in "${ATESTCASES[@]}"
do
    TFILE="${TESTDIR}/test${TC}a"
    printf "Test %s..." "${TC}"
    COMM="./run ${TFILE}.k- > ${TFILE}.out"
    if [ -f "${TFILE}.in" ]
    then
        COMM="${COMM} < ${TFILE}.in"
    fi

    eval "${COMM}"

    eval "diff ${TFILE}.ans ${TFILE}.out > /dev/null"
    result $?
done
echo ''

echo "# Testing Exercise 2"
for TC in "${TC2[@]}"
do
    TFILE="${EXDIR}/test2-${TC}"
    printf "Test %s..." "${TC}"

    if [ -f "${EXDIR}/ex2.txt" ]
    then
        SRC="${EXDIR}/ex2.txt"
    else
        SRC="${EXDIR}/ex2.k-"
    fi

    COMM="./run ${SRC} < ${TFILE}.in > ${TFILE}.out"

    eval "${COMM}"

    eval "diff ${TFILE}.ans ${TFILE}.out > /dev/null"
    if [ "$?" == 1 ]
    then
        echo "${WRONG}"
        echo "answer:"
        cat "${TFILE}.ans"
        echo "output:"
        cat "${TFILE}.out"
    else
        echo "${CORRECT}"
    fi
done
echo ''

echo "# Testing Exercise 3"
for TC in "${TC3[@]}"
do
    TFILE="${EXDIR}/test3-${TC}"
    printf "Test %s..." "${TC}"
    if [ -f "${EXDIR}/ex3.txt" ]
    then
        SRC="${EXDIR}/ex3.txt"
    else
        SRC="${EXDIR}/ex3.k-"
    fi

    sed -e "/2017/ r ${TFILE}.k-" -e "s/2017//" "${SRC}" > "${TFILE}.tmp.k-"

    COMM="./run ${TFILE}.tmp.k- > ${TFILE}.out"

    eval "${COMM}"

    rm "${TFILE}.tmp.k-"

    eval "diff ${TFILE}.ans ${TFILE}.out > /dev/null"
    result $?
done
