#!/bin/bash

TESTCASES=(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25)
GC_TESTCASES=(1 2)
TESTDIR="examples"
WRONG="$(tput setaf 1)✗$(tput sgr0)"
CORRECT="$(tput setaf 2)✓$(tput sgr0)"

function result {
    if [ 0 -lt "$1"  ]
    then
        echo "${WRONG}"
    else
        echo "${CORRECT}"
    fi
}

echo '# Compiling...'
make

echo '# Testing SM5 translator'

for TC in "${TESTCASES[@]}"
do
    TFILE="${TESTDIR}/test${TC}"
    printf "Test %s..." "${TC}"
    COMM="./run ${TFILE}.k-- > ${TFILE}.out"
    COMMK="./run -k ${TFILE}.k-- > ${TFILE}.ans"
    if [ -f "${TFILE}.in" ]
    then
        COMM="${COMM} < ${TFILE}.in"
        COMMK="${COMMK} < ${TFILE}.in"
    fi

    eval "${COMMK}"

    if eval "${COMM}"
    then
        eval "diff ${TFILE}.ans ${TFILE}.out > /dev/null"
        result $?
    else
        echo "${WRONG}"
    fi
done

echo '# Testing SM5 Limited: gc'

for TC in "${GC_TESTCASES[@]}"
do
    TFILE="${TESTDIR}/testgc${TC}"
    printf "Test %s..." "${TC}"
    COMM="./run -gc ${TFILE}.k-- > ${TFILE}.out"
    COMMK="./run -k ${TFILE}.k-- > ${TFILE}.ans"
    if [ -f "${TFILE}.in" ]
    then
        COMM="${COMM} < ${TFILE}.in"
        COMMK="${COMMK} < ${TFILE}.in"
    fi

    eval "${COMMK}"

    if eval "${COMM}"
    then
        eval "diff ${TFILE}.ans ${TFILE}.out > /dev/null"
        result $?
    else
        echo "${WRONG}"
    fi
done
